---
appPort: 8009
metricsPort: 8010
s3:
  region: us-west-rack1
  bucket: images
  endpoint: http://localhost:9000
  pathStyle: true
  user: admin
  secret: admin-devops
  imgPath: /tmp/thumbnail.png
db:
  user: go-app
  password: password
  host: ""
  database: mydb
redis:
  username: 
  password: password
  host: redis-service
  port: 6379
  database: 0